import React from "react";

/**
 * Minimal props for each bpm key — enough to render without throwing.
 * Required props are provided; optional props are omitted.
 * Used by the smoke render gate.
 */
export const FIXTURES: Record<string, Record<string, unknown>> = {
  // ── Core components defined in bpm.tsx ──────────────────────────────────
  page: { children: "test content" },
  title: { children: "Test Title" },
  chat: {},

  // ── Title variants ──────────────────────────────────────────────────────
  title1: { children: "H1" },
  title2: { children: "H2" },
  title3: { children: "H3" },
  title4: { children: "H4" },
  titleBpm: { children: "Title" },

  // ── Metrics ─────────────────────────────────────────────────────────────
  metricRow: { children: React.createElement("span", null, "metric") },
  metric: { label: "Revenue", value: 42 },

  // ── Table ────────────────────────────────────────────────────────────────
  table: { columns: [], data: [] },

  // ── All-optional components ──────────────────────────────────────────────
  accordion: {},
  addressInput: {},
  altairChart: {},
  avatar: {},
  breadcrumb: {},
  button: {},
  card: {},
  checkbox: {},
  colorPicker: {},
  column: {},
  dateInput: {},
  dateRangePicker: {},
  divider: {},
  emailComposer: {},
  empty: {},
  emptyState: {},
  fab: {},
  fileUploader: {},
  grid: {},
  gps: {},
  image: {},
  input: {},
  loadingBar: {},
  map: {},
  nfcBadge: {},
  numberInput: {},
  plcConnector: {},
  plotlyChart: {},
  progress: {},
  radioGroup: {},
  rating: {},
  richTextEditor: {},
  selectbox: {},
  signaturePad: {},
  skeleton: {},
  slider: {},
  spinner: {},
  spinnerDot: {},
  stepper: {},
  text: {},
  textarea: {},
  theme: {},
  timeInput: {},
  timeline: {},
  topNav: {},
  transition: {},
  treeview: {},
  video: {},
  assistantPanel: {},
  offlineIndicator: {},

  // ── Components requiring children ────────────────────────────────────────
  badge: { children: "Status" },
  caption: { children: "Caption text" },
  container: { children: "content" },
  free: { name: "GateZone", children: "zone libre" },
  drawer: { children: "drawer content", open: false, onClose: () => {} },
  expander: { title: "Section", children: "section content" },
  message: { children: "A message" },
  modal: { isOpen: false, onClose: () => {}, children: "modal content" },
  panel: {},
  printLayout: { children: "print content" },
  scrollContainer: { children: "scroll content" },
  toggle: {},

  // ── Components with required props ───────────────────────────────────────
  activityFeed: { activities: [] },
  aiQueryBar: { onQuery: async () => "response" },
  alarmPanel: { alarms: [] },
  anomalyAlert: { expected: 10, actual: 12 },
  approvalFlow: { steps: [] },
  areaChart: { data: [] },
  audio: { src: "test.mp3" },
  autocomplete: { options: [] },
  barChart: { data: [{ label: "A", value: 1 }] },
  barcode: { value: "123456" },
  breadcrumbs: { items: [] },
  changelog: { changes: [] },
  chatInterface: { messages: [], onSend: () => {} },
  chip: { label: "Tag" },
  codeBlock: { code: "const x = 1;" },
  codeEditor: { value: "// code", onChange: () => {} },
  commentThread: {
    comments: [],
    onPost: () => {},
    currentUser: { id: "1", name: "User" },
  },
  commandPalette: { commands: [], onClose: () => {} },
  comparison: { items: [], dimensions: [] },
  confirmModal: {
    isOpen: false,
    onConfirm: () => {},
    onCancel: () => {},
    title: "Confirm",
    message: "Are you sure?",
  },
  contextMenu: { items: [], trigger: "click me" },
  crud: { title: "Items", endpoint: "/api/items", columns: [], fields: [] },
  dataExplorer: { data: [], columns: [] },
  decisionTree: { rootId: "root", nodes: [], onNodeClick: () => {} },
  diffViewer: { original: "old text", modified: "new text" },
  drillDown: {
    levels: [],
    currentLevel: 0,
    onDrill: () => {},
    onBack: () => {},
  },
  exportButton: { data: [], filename: "export" },
  filePreview: { url: "", filename: "test.pdf" },
  filterPanel: { filters: [], onChange: () => {}, onReset: () => {} },
  flowDiagram: { states: [], transitions: [] },
  funnelChart: { stages: [] },
  gantt: { tasks: [], viewMode: "day", onTaskClick: () => {} },
  geofence: { zones: [], center: [48.85, 2.35] },
  groupedList: { items: [], groupBy: "id", renderItem: () => null },
  heatmap: {
    data: [[0]],
    xLabels: ["X"],
    yLabels: ["Y"],
    colorScale: { min: "#ffffff", max: "#000000" },
  },
  highlightBox: { value: 1, label: "KPI", title: "Title" },
  html: { html: "<p>test</p>" },
  inlineEdit: { value: "edit me", onSave: () => {} },
  invoiceTemplate: { issuer: "Company A", client: "Client B", lines: [] },
  jsonEditor: { value: "{}", onChange: () => {} },
  jsonViewer: { data: { key: "value" } },
  labelValue: { label: "Status", value: "Active" },
  lineChart: { data: [] },
  liveChart: { data: [] },
  liveGauge: { value: 75 },
  locationField: {},
  machineStatus: { title: "Machine A", state: "running" },
  mapView: {},
  markdown: { text: "# Hello\nWorld" },
  masterDetail: {
    items: [],
    columns: [],
    renderDetail: () => React.createElement("span", null, "detail"),
    onSelect: () => {},
  },
  modelSelector: { models: [], selected: "", onChange: () => {} },
  notificationCenter: { notifications: [], onMarkRead: () => {} },
  orgChart: { nodes: [] },
  pagination: { page: 1, totalPages: 5, onPageChange: () => {} },
  pageLayout: { title: "Dashboard", items: [] },
  pdfViewer: { src: "" },
  pivotTable: { data: [], rowKey: "row", colKey: "col", valueKey: "val" },
  popover: { trigger: "hover me", children: "popover content" },
  predictiveChart: { historical: [], predicted: [] },
  progressRing: { value: 50 },
  promptInput: { value: "", onChange: () => {}, onSubmit: () => {} },
  qrCode: { value: "https://example.com" },
  radarChart: { axes: ["A", "B", "C"], values: [1, 2, 3] },
  relationGraph: { nodes: [], edges: [] },
  reportPage: { title: "Report", sections: [] },
  routePlanner: { stops: [] },
  scatterChart: { data: [] },
  scheduler: {
    view: "week",
    events: [],
    onEventClick: () => {},
    onSlotClick: () => {},
  },
  sensorGrid: { sensors: [] },
  sparkline: { values: [1, 2, 3] },
  splitView: { left: "left content", right: "right content" },
  stateMachine: { states: ["idle", "running"], transitions: [], currentState: "idle" },
  statusBox: { label: "System Status" },
  statusTracker: { stages: [] },
  streamingText: { content: "Hello world" },
  suggestionCard: { title: "Suggestion", description: "Details here", actions: [] },
  tabs: { tabs: [] },
  toast: { message: "Saved!", onClose: () => {} },
  tooltip: { text: "Tooltip info", children: "hover me" },
  tour: { steps: [], isActive: false },
  treemap: { data: [] },
  waterfall: { data: [] },
  wizardForm: { steps: [], onComplete: () => {} },
};
