import React,{act} from "react";import {createRoot,type Root} from "react-dom/client";import {beforeEach,afterEach,it,expect,vi} from "vitest";import {WaterObject} from "../src/objects/WaterObject";
const mocked=vi.hoisted(()=>({create:vi.fn(),draw:vi.fn()}));vi.mock("../src/objects/water-renderer",()=>({createWaterField:mocked.create}));
let root:Root,element:HTMLDivElement,intersection:(e:{isIntersecting:boolean}[])=>void,mediaChange:()=>void,reduced=false,coarse=false;
beforeEach(()=>{vi.useFakeTimers({toFake:["setTimeout","clearTimeout","performance"]});vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT",true);mocked.create.mockReset();mocked.draw.mockReset();mocked.create.mockImplementation((size:number)=>({draw:mocked.draw.mockImplementation(()=>new Uint8ClampedArray(size*size*4))}));vi.stubGlobal("IntersectionObserver",class{constructor(cb:typeof intersection){intersection=cb;}observe(){}disconnect(){}});vi.stubGlobal("matchMedia",(q:string)=>({get matches(){return q.includes("reduced-motion")?reduced:q.includes("pointer: coarse")&&coarse;},addEventListener(_e:string,cb:()=>void){if(q.includes("reduced-motion"))mediaChange=cb;},removeEventListener(){}}));vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,blob:async()=>new Blob()}));vi.stubGlobal("createImageBitmap",vi.fn().mockResolvedValue({width:4,height:4,close:vi.fn()}));vi.spyOn(HTMLCanvasElement.prototype,"getContext").mockImplementation(()=>({drawImage(){},getImageData(){return {data:new Uint8ClampedArray(64)};},createImageData(w:number,h:number){return {data:new Uint8ClampedArray(w*h*4)};},putImageData(){}} as unknown as CanvasRenderingContext2D));reduced=false;coarse=false;element=document.createElement("div");document.body.append(element);root=createRoot(element);});
afterEach(async()=>{await act(async()=>root.unmount());element.remove();vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks();});async function show(){await act(async()=>intersection([{isIntersecting:true}]));await act(async()=>vi.dynamicImportSettled());}
it("uses one capped mobile loop and honors reduced motion",async()=>{coarse=true;reduced=true;await act(async()=>root.render(<WaterObject id="water-wave" label="Wave" size={420}/>));await show();expect(mocked.create.mock.calls[0][0]).toBe(224);expect(vi.getTimerCount()).toBe(0);reduced=false;await act(async()=>mediaChange());expect(vi.getTimerCount()).toBe(1);await act(async()=>vi.advanceTimersByTime(1000));expect(mocked.draw.mock.calls.length).toBeLessThanOrEqual(15);});
it("keeps thumbnails fixed and defers the renderer until visible",async()=>{await act(async()=>root.render(<WaterObject id="water-ripple" label="Ripple" thumbnail/>));expect(mocked.create).not.toHaveBeenCalled();expect(element.querySelector("canvas")).toBeNull();expect(vi.getTimerCount()).toBe(0);});
it("freezes exact time on pause and stops offscreen",async()=>{await act(async()=>root.render(<WaterObject id="water-waterfall" label="Falls"/>));await show();await act(async()=>vi.advanceTimersByTime(500));const t=mocked.draw.mock.calls.at(-1)![2];await act(async()=>root.render(<WaterObject id="water-waterfall" label="Falls" playing={false}/>));expect(vi.getTimerCount()).toBe(0);expect(mocked.draw.mock.calls.at(-1)![2]).toBe(t);await act(async()=>root.render(<WaterObject id="water-waterfall" label="Falls"/>));await act(async()=>intersection([{isIntersecting:false}]));expect(vi.getTimerCount()).toBe(0);});
it("retains a readable fallback after renderer failure",async()=>{mocked.create.mockImplementation(()=>{throw Error("no canvas");});await act(async()=>root.render(<WaterObject id="water-whirlpool" label="Tourbillon"/>));await show();expect(element.textContent).toContain("animation indisponible");expect(element.querySelector("img")?.alt).toBe("Tourbillon");expect(vi.getTimerCount()).toBe(0);});
