"use client";
import React from "react";
import { moleculeGraph, MOLECULE_PRESETS, moleculePresetSettings } from "./molecule-presets";
import { DEFAULT_MOLECULE_SETTINGS, MOLECULE_ELEMENTS, moleculeWarnings, type MoleculeGraph, type MoleculeSettings, type MolecularElement } from "./molecules";

const input: React.CSSProperties = { minHeight: 40, minWidth: 0, maxWidth: "100%", border: "1px solid currentColor", borderRadius: 7, background: "transparent", color: "inherit", padding: "5px 8px" };
export function MoleculeControls({ value = DEFAULT_MOLECULE_SETTINGS, onChange, locale = "fr" }: { value?: MoleculeSettings; onChange: (value: MoleculeSettings) => void; locale?: "fr" | "en" }) {
  const fr = locale === "fr", graph = moleculeGraph(value), warnings = moleculeWarnings(graph);
  const edit = (next: MoleculeGraph) => onChange({ ...value, preset: "custom", graph: next });
  const labels = fr ? { atoms: "Atomes", bonds: "Liaisons", labels: "Symboles", measurements: "Mesures 3D" } : { atoms: "Atoms", bonds: "Bonds", labels: "Symbols", measurements: "3D measurements" };
  return <div style={{ display: "grid", gap: 14 }}>
    <label>{fr ? "Molécule" : "Molecule"}<select aria-label={fr ? "Molécule" : "Molecule"} style={{ ...input, display: "block", width: "100%" }} value={value.preset} onChange={e => { const preset = e.target.value as MoleculeSettings["preset"]; if (preset !== "custom") onChange(moleculePresetSettings(preset)); }}>
      {Object.entries(MOLECULE_PRESETS).map(([key, p]) => <option key={key} value={key}>{p.formula} · {p.name[locale]}</option>)}{value.preset === "custom" && <option value="custom">{fr ? "Composition libre (non validée)" : "Custom (unvalidated)"}</option>}
    </select></label>
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>{(["atoms", "bonds", "labels", "measurements"] as const).map(key => <label key={key}><input type="checkbox" checked={value.layers[key]} onChange={e => onChange({ ...value, layers: { ...value.layers, [key]: e.target.checked } })}/> {labels[key]}</label>)}</div>
    {(["yaw", "pitch"] as const).map(key => <label key={key}>{key === "yaw" ? (fr ? "Orientation" : "Orientation") : (fr ? "Inclinaison" : "Tilt")} {value[key]}°<input aria-label={key === "yaw" ? (fr ? "Orientation" : "Orientation") : (fr ? "Inclinaison" : "Tilt")} type="range" min={key === "yaw" ? -180 : -90} max={key === "yaw" ? 180 : 90} value={value[key]} onChange={e => onChange({ ...value, [key]: Number(e.target.value) })} style={{ width: "100%" }}/></label>)}
    <p style={{ fontSize: 12, margin: 0 }}>{fr ? "H blanc, O rouge, C gris, N bleu. Les couleurs et tailles des boules sont conventionnelles. L’orientation ne modifie pas les mesures 3D." : "H white, O red, C grey, N blue. Ball colours and sizes are conventional. Orientation does not change 3D measurements."}</p>
    <details><summary style={{ cursor: "pointer", padding: "10px 0" }}>{fr ? "Composer les atomes et les liaisons" : "Compose atoms and bonds"}</summary>
      <p style={{ fontSize: 12 }}>{fr ? "Coordonnées cartésiennes en Å (±50). Toute modification crée une composition non validée ; aucun calcul de stabilité, de charge ou d’orbitale moléculaire n’est effectué." : "Cartesian coordinates in Å (±50). Every edit creates an unvalidated composition; no stability, charge or molecular orbital calculation is performed."}</p>
      {graph.atoms.map((atom, index) => <fieldset key={atom.id} style={{ margin: "10px 0", padding: 8, border: "1px solid currentColor", borderRadius: 8 }}><legend>{atom.id}</legend>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: 5 }}><label>{fr ? "Élément" : "Element"}<select aria-label={`${atom.id} element`} style={{ ...input, width: "100%" }} value={atom.element} onChange={e => edit({ ...graph, atoms: graph.atoms.map((a, i) => i === index ? { ...a, element: e.target.value as MolecularElement } : a) })}>{MOLECULE_ELEMENTS.map(e => <option key={e}>{e}</option>)}</select></label>
          {([0, 1, 2] as const).map(axis => <label key={axis}>{["x", "y", "z"][axis]}<input aria-label={`${atom.id} ${["x", "y", "z"][axis]} Å`} type="number" min="-50" max="50" step="0.01" value={atom.position[axis]} style={{ ...input, width: "100%", boxSizing: "border-box" }} onChange={e => { const n = e.target.valueAsNumber; if (Number.isFinite(n) && Math.abs(n) <= 50) edit({ ...graph, atoms: graph.atoms.map((a, i) => i === index ? { ...a, position: a.position.map((v, j) => j === axis ? n : v) as [number, number, number] } : a) }); }}/></label>)}
        </div><button type="button" style={{ ...input, marginTop: 6 }} disabled={graph.atoms.length <= 1} onClick={() => edit({ atoms: graph.atoms.filter(a => a.id !== atom.id), bonds: graph.bonds.filter(b => b.from !== atom.id && b.to !== atom.id) })}>{fr ? "Retirer" : "Remove"} {atom.id}</button>
      </fieldset>)}
      <button type="button" style={input} disabled={graph.atoms.length >= 24} onClick={() => { let n = 1; while (graph.atoms.some(a => a.id === `A${n}`)) n++; edit({ ...graph, atoms: [...graph.atoms, { id: `A${n}`, element: "H", position: [0, graph.atoms.length * .4, 0] }] }); }}>{fr ? "+ Ajouter un atome" : "+ Add atom"}</button>
      <div style={{ display: "grid", gap: 6, marginTop: 12 }}>{graph.bonds.map((bond, i) => <div key={`${bond.from}-${bond.to}`} style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}><span>{bond.from}—{bond.to}</span><select aria-label={`${bond.from}-${bond.to} order`} style={input} value={bond.order} onChange={e => edit({ ...graph, bonds: graph.bonds.map((b, j) => j === i ? { ...b, order: Number(e.target.value) as 1 | 2 | 3 } : b) })}>{[1, 2, 3].map(o => <option key={o} value={o}>{o}</option>)}</select><button type="button" style={input} onClick={() => edit({ ...graph, bonds: graph.bonds.filter((_, j) => j !== i) })}>{fr ? "Retirer" : "Remove"}</button></div>)}</div>
      <label style={{ display: "block", marginTop: 12 }}>{fr ? "Ajouter une liaison" : "Add bond"}<select aria-label={fr ? "Ajouter une liaison" : "Add bond"} value="" style={{ ...input, width: "100%" }} disabled={graph.bonds.length >= 48} onChange={e => { if (!e.target.value) return; const [from, to] = e.target.value.split(":"); edit({ ...graph, bonds: [...graph.bonds, { from, to, order: 1 }] }); }}><option value="">{fr ? "Choisir deux atomes…" : "Choose two atoms…"}</option>{graph.atoms.flatMap((a, i) => graph.atoms.slice(i + 1).filter(b => !graph.bonds.some(edge => [edge.from, edge.to].includes(a.id) && [edge.from, edge.to].includes(b.id))).map(b => <option key={`${a.id}:${b.id}`} value={`${a.id}:${b.id}`}>{a.id}—{b.id}</option>))}</select></label>
    </details>
    <p role="status" style={{ fontSize: 12, margin: 0 }}>{value.preset === "custom" ? (fr ? "Composition non validée." : "Unvalidated composition.") : (fr ? "Géométrie gazeuse sourcée — NIST CCCBDB." : "Sourced gas-phase geometry — NIST CCCBDB.")} {warnings.length ? (fr ? "Attention : " : "Warning: ") + warnings.join(", ") : ""}</p>
  </div>;
}
