"use client";
import React,{useEffect,useState} from "react";
import {PlanetObject} from "../../packages/core/src/objects/PlanetObject";
import styles from "./ObjectsCatalogue.module.css";
type Entry={id:string;name:string;family:string;kind:string;license:string;sourceUrl:string;status:string;sha256:string;author:{name:string|null}};
export function ObjectContributions({locale}:{locale:"fr"|"en"}){
 const [active,setActive]=useState<Entry|null>(null),[cursor,setCursor]=useState<string|null>(null),[theme,setTheme]=useState("all");
 const fr=locale==="fr",[objects,setObjects]=useState<Entry[]>([]),[mine,setMine]=useState(false),[canReview,setCanReview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch(`/api/objects/contributions${mine?'?scope=mine':''}`,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setObjects(d.objects);setCursor(d.nextCursor??null);setCanReview(d.canReview);}).catch(e=>{if(!controller.signal.aborted){setObjects([]);setMessage(fr?'Bibliothèque indisponible. Connectez-vous pour consulter vos propositions.':'Library unavailable. Sign in to view your submissions.');}});return()=>controller.abort();},[mine,revision]);
 async function more(){if(!cursor||busy)return;setBusy(true);try{const r=await fetch(`/api/objects/contributions?cursor=${cursor}${mine?'&scope=mine':''}`),d=await r.json();if(!r.ok)throw Error();setObjects(prev=>[...prev,...d.objects]);setCursor(d.nextCursor??null);}catch{setMessage(fr?'Impossible de charger la suite.':'Unable to load more.');}finally{setBusy(false);}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;setBusy(true);setMessage("");try{const r=await fetch('/api/objects/contributions',{method:'POST',body:new FormData(form)}),d=await r.json();if(!r.ok)throw Error(d.error);form.reset();setMine(true);setRevision(n=>n+1);setMessage(fr?'Objet enregistré. Il sera visible par tous après validation.':'Object saved. It will be visible to everyone after review.');}catch(e){setMessage(e instanceof Error?e.message:'Enregistrement impossible');}finally{setBusy(false);}}
 async function review(id:string,status:string){setBusy(true);try{const r=await fetch(`/api/objects/contributions/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})}),d=await r.json();if(!r.ok)throw Error(d.error);setRevision(n=>n+1);}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}finally{setBusy(false);}}
 function download(o:Entry){const data={schemaVersion:1,kind:"modular-object",id:o.id,version:"1.0.0",sha256:o.sha256,style:"photorealistic",animation:{playing:true,speed:1}};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=`${o.id}.modular.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 return <section className={styles.contribute}><h2>{fr?'Créés par la communauté':'Created by the community'}</h2>
  <div className={styles.tabs}><button type="button" aria-pressed={!mine} onClick={()=>{setMine(false);setMessage('');}}>{fr?'Bibliothèque publique':'Public library'}</button><button type="button" aria-pressed={mine} onClick={()=>{setMine(true);setMessage('');}}>{fr?'Mes propositions':'My submissions'}</button></div>
  <label>{fr?"Thématique des créations":"Contribution theme"}<select value={theme} onChange={e=>setTheme(e.target.value)}>{[["all","Tout","All"],["space","Univers","Universe"],["buildings","Bâtiments","Buildings"],["mobility","Mobilité","Mobility"],["logistics","Logistique","Logistics"],["nature","Nature","Nature"],["characters","Personnages","Characters"],["other","Autres","Other"]].map(([v,f,e])=><option key={v} value={v}>{fr?f:e}</option>)}</select></label>
  {active&&<div className={styles.stage}><PlanetObject id="mercury" label={active.name} textureUrl={`/api/objects/contributions/${active.id}/image`} size={400}/><button type="button" onClick={()=>setActive(null)}>{fr?"Fermer":"Close"}</button></div>}<div className={styles.communityGrid}>{objects.filter(o=>theme==="all"||o.family===theme).map(o=><article key={o.id} className={styles.communityCard}><img src={`/api/objects/contributions/${o.id}/image`} alt={o.name} loading="lazy"/><h3>{o.name}</h3>{o.kind==="planet-texture"&&<button type="button" onClick={()=>setActive(o)}>{fr?"Explorer en rotation":"Explore rotation"}</button>}{o.status==="published"&&<button type="button" onClick={()=>download(o)}>{fr?"Ajouter à Maker":"Add to Maker"}</button>}<p>{o.author.name??(fr?'Contributeur':'Contributor')} · {o.license}</p>{o.sourceUrl&&<a href={o.sourceUrl} target="_blank" rel="noreferrer">{fr?'Source et crédits':'Source and credits'}</a>}{mine&&<p>{o.status==='pending'?(fr?'En validation':'In review'):o.status==='published'?(fr?'Publié':'Published'):(fr?'Non retenu':'Not accepted')}</p>}{canReview&&o.status==='pending'&&<div className={styles.actions}><button type="button" disabled={busy} onClick={()=>review(o.id,'published')}>{fr?'Publier':'Publish'}</button><button type="button" disabled={busy} onClick={()=>review(o.id,'rejected')}>{fr?'Refuser':'Reject'}</button></div>}</article>)}</div>
  {cursor&&<button type="button" disabled={busy} onClick={more}>{fr?"Voir plus d’objets":"Load more objects"}</button>}
  {objects.length===0&&!message&&<p>{fr?'La collection attend vos premières créations.':'The collection is ready for your first creations.'}</p>}
  <h2>{fr?'Proposer un objet':'Contribute an object'}</h2><p>{fr?'Ajoutez votre création ou un asset réutilisable. Les images détourées sont recommandées ; les textures de planètes doivent couvrir toute la surface au format 2:1.':'Add your own creation or a reusable asset. Transparent images are recommended; planet textures need a full 2:1 surface map.'}</p>
  <form onSubmit={submit}>
   <label>{fr?'Nom de l’objet':'Object name'}<input name="name" required minLength={2} maxLength={100}/></label>
   <label>{fr?'Thématique':'Theme'}<select name="family">{[['space','Univers','Universe'],['buildings','Bâtiments','Buildings'],['mobility','Mobilité','Mobility'],['logistics','Logistique','Logistics'],['nature','Nature','Nature'],['characters','Personnages','Characters'],['other','Autres','Other']].map(([v,f,e])=><option key={v} value={v}>{fr?f:e}</option>)}</select></label>
   <label>{fr?'Type d’objet':'Object type'}<select name="kind"><option value="image">{fr?'Illustration / objet détouré':'Illustration / cutout'}</option><option value="planet-texture">{fr?'Texture de planète (2:1)':'Planet texture (2:1)'}</option></select></label>
   <label>{fr?'Fichier · PNG, JPEG, WebP · 10 Mo max.':'File · PNG, JPEG, WebP · max. 10 MB'}<input name="file" type="file" accept="image/png,image/jpeg,image/webp" required/></label>
   <label>{fr?'Licence':'License'}<select name="license"><option value="CC0-1.0">CC0</option><option value="CC-BY-4.0">CC BY 4.0</option></select></label>
   <label>{fr?'Source — facultative pour votre propre création':'Source — optional for your own creation'}<input name="sourceUrl" type="url" placeholder="https://…" maxLength={2048}/></label>
   <label style={{gridColumn:'1/-1',flexDirection:'row',alignItems:'flex-start'}}><input type="checkbox" name="rightsConfirmed" value="true" required/>{fr?'Je dispose des droits permettant la modification et la redistribution de cet objet sous la licence choisie.':'I hold the rights to allow modification and redistribution under the selected license.'}</label>
   <button type="submit" disabled={busy}>{busy?(fr?'Enregistrement…':'Saving…'):(fr?'Proposer à la bibliothèque':'Submit to library')}</button>
  </form><p role="status">{message}</p>
 </section>;
}
