import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {FloraObject} from "../packages/core/src/objects/FloraObject";
import {FLORA_IDS,FLORA_NAMES,type FloraId,type FloraStyle} from "../packages/core/src/objects/flora";
function Preview(){const [id,setId]=useState<FloraId>("flora-fern"),[style,setStyle]=useState<FloraStyle>("photorealistic"),[playing,setPlaying]=useState(true),[dark,setDark]=useState(true),[size,setSize]=useState(420),[speed,setSpeed]=useState(1);
return <main style={{fontFamily:"system-ui",background:dark?"#071811":"#f4f0e6",color:dark?"#edf6ee":"#17352e",minHeight:"180vh",padding:24}}><h1>Végétation vivante</h1><p>Une transformation locale principale et un détail secondaire au maximum. Vignettes fixes.</p>
<div style={{display:"flex",gap:12,flexWrap:"wrap"}}><label>Objet <select value={id} onChange={e=>setId(e.target.value as FloraId)}>{FLORA_IDS.map(i=><option key={i}>{i}</option>)}</select></label><label>Style <select value={style} onChange={e=>setStyle(e.target.value as FloraStyle)}><option value="photorealistic">Studio botanique</option><option value="illustration">Illustration</option></select></label><button onClick={()=>setPlaying(!playing)}>{playing?"Pause":"Reprendre"}</button><button onClick={()=>setDark(!dark)}>Fond {dark?"clair":"sombre"}</button><label>Format <select value={size} onChange={e=>setSize(+e.target.value)}><option value="420">420 px</option><option value="160">160 px</option></select></label><label>Vitesse <select value={speed} onChange={e=>setSpeed(+e.target.value)}><option value=".5">× 0,5</option><option value="1">× 1</option><option value="2">× 2</option></select></label></div>
<FloraObject id={id} label={FLORA_NAMES[id].fr} style={style} size={size} playing={playing} speed={speed}/><div style={{display:"flex",flexWrap:"wrap"}}>{FLORA_IDS.map(i=><button key={i} onClick={()=>setId(i)} style={{background:"transparent",color:"inherit",border:"1px solid #8191a355",borderRadius:12,margin:5}}><FloraObject id={i} label={FLORA_NAMES[i].fr} style={style} size={120} thumbnail/><div>{FLORA_NAMES[i].fr}</div></button>)}</div><p>Faire défiler vérifie l’arrêt hors écran. Les préférences reduced motion figent la scène.</p></main>}
createRoot(document.getElementById("root")!).render(<Preview/>);
