// Pass a directory of original SVGs to rebuild derivatives; without it, verify and regenerate catalogue.
import {readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import sharp from 'sharp';
const root=new URL('../public/objects/flags-v1/',import.meta.url),m=JSON.parse(await readFile(new URL('manifest.json',root),'utf8'));
for(const a of m.assets){
 if(process.argv[2]){const source=await readFile(process.argv[2]+'/'+a.id+'.svg');if(createHash('sha256').update(source).digest('hex')!==a.sourceSha256)throw Error('Source hash '+a.id);
 const {data,info}=await sharp(source,{limitInputPixels:false}).resize({width:768,height:768,fit:'inside'}).webp({lossless:true}).toBuffer({resolveWithObject:true});
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${info.width}" height="${info.height}" viewBox="0 0 ${info.width} ${info.height}"><image width="${info.width}" height="${info.height}" href="data:image/webp;base64,${data.toString('base64')}"/></svg>\n`;
 await writeFile(new URL(a.id+'.svg',root),svg);a.width=info.width;a.height=info.height;a.runtimeBytes=Buffer.byteLength(svg);a.runtimeSha256=createHash('sha256').update(svg).digest('hex');
 }
 const runtime=await readFile(new URL(a.id+'.svg',root));if(createHash('sha256').update(runtime).digest('hex')!==a.runtimeSha256)throw Error('Runtime hash '+a.id);
}
await writeFile(new URL('manifest.json',root),JSON.stringify(m,null,2)+'\n');
await writeFile(new URL('../packages/core/src/objects/flags.generated.ts',import.meta.url),'// Generated by scripts/generate-flags.mjs; do not edit.\nexport const FLAG_DESIGNS = '+JSON.stringify(m.assets.map(({id,name,group,ratio})=>({id,name,group,ratio})))+' as const;\n');
