"""Reproducible factual data import, no third-party text/artwork or runtime requests.
PubChem-generated 3D conformers: https://pubchem.ncbi.nlm.nih.gov/docs/pubchem3d
NCBI distribution statement and caveats are retained in scientific-composition.md.
Run: python scripts/import-science-data.py [--cache /path/to/cache]
"""
import argparse
import hashlib
import json
import pathlib
import re
import time
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--cache', default='/tmp/blueprint-pubchem-records')
parser.add_argument('--offline', action='store_true', help='Use cached responses and retain recorded exclusions; no network')
args = parser.parse_args()
cache = pathlib.Path(args.cache)
cache.mkdir(parents=True, exist_ok=True)
out = ROOT / 'packages/core/src/objects'
elements = {1:'H',6:'C',7:'N',8:'O',9:'F',15:'P',16:'S',17:'Cl',35:'Br',53:'I'}
old_manifest=ROOT/'docs/previews/science/molecular-sources.json'
old_exclusions={e['id']:e['reason'] for e in json.loads(old_manifest.read_text()).get('excluded',[])} if old_manifest.exists() else {}

def download(url, key):
    file = cache / (key + '.json')
    if args.offline and not file.exists():
        raise ValueError(old_exclusions.get(key,'No cached response; excluded in offline mode'))
    if not file.exists():
        for attempt in range(3):
            try:
                time.sleep(.3)  # strictly sequential, below PubChem's 5 requests/s
                request = urllib.request.Request(url, headers={'User-Agent':'BlueprintModular-data-import/1.0'})
                with urllib.request.urlopen(request, timeout=40) as response:
                    raw = response.read(2_000_001)
                if len(raw) > 2_000_000:
                    raise ValueError('oversize record')
                file.write_bytes(raw)
                break
            except Exception:
                if attempt == 2:
                    raise
                time.sleep(2 ** attempt)
    raw = file.read_bytes()
    return json.loads(raw), hashlib.sha256(raw).hexdigest()

records, provenance, excluded, seen = [], [], [], set()
for en, fr in json.loads((ROOT/'scripts/molecule-seeds.json').read_text()):
    key = re.sub(r'[^a-z0-9]+', '-', en.lower()).strip('-')
    url = 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/' + urllib.parse.quote(en, safe='') + '/record/JSON?record_type=3d'
    try:
        data, digest = download(url, key)
        if len(data['PC_Compounds']) != 1:
            raise ValueError('ambiguous name; use a specific CID')
        p = data['PC_Compounds'][0]
        cid = p['id']['id']['cid']
        if cid in seen:
            raise ValueError('duplicate CID')
        a = p['atoms']
        if not 2 <= len(a['aid']) <= 48 or p.get('charge',0) or any(q.get('value',0) for q in a.get('charge',[])) or a.get('isotope'):
            raise ValueError('unsupported atom count, formal charge or isotope')
        c = p['coords'][0]
        xyz = c['conformers'][0]
        if 2 not in c['type'] or len(xyz.get('z',[])) != len(a['aid']):
            raise ValueError('missing 3D conformer')
        positions = dict(zip(c['aid'], zip(xyz['x'],xyz['y'],xyz['z'])))
        atoms = [[elements[e], *positions[i]] for i,e in zip(a['aid'],a['element'])]
        ids = {aid:i for i,aid in enumerate(a['aid'])}
        b = p.get('bonds',{})
        bonds = [[ids[i],ids[j],o] for i,j,o in zip(b.get('aid1',[]),b.get('aid2',[]),b.get('order',[]))]
        if not bonds or len(bonds)>96 or any(o not in (1,2,3) for i,j,o in bonds):
            raise ValueError('unsupported bonds')
        conformer = next((d['value']['sval'] for d in xyz.get('data',[]) if d['urn'].get('label')=='Conformer' and d['urn'].get('name')=='ID'), None)
        if not conformer:
            raise ValueError('missing PubChem-generated conformer identifier')
        records.append([key,fr,en,cid,atoms,bonds])
        provenance.append({'id':key,'cid':cid,'conformer':conformer,'request':url,'sha256':digest,'author':'PubChem / NCBI','method':'PubChem3D computed conformer; not experimental or guaranteed energy minimum'})
        seen.add(cid)
        print('OK',key,cid,len(atoms),flush=True)
    except Exception as error:
        excluded.append({'id':key,'reason':str(error)})
        print('SKIP',key,str(error),flush=True)

header = '// Generated by scripts/import-science-data.py; do not edit. Factual PubChem 3D coordinates.\n'
record_type='import type {MolecularElement} from "./molecules";\ntype LibraryRecord = readonly [string,string,string,number,readonly (readonly [MolecularElement,number,number,number])[],readonly (readonly [number,number,1|2|3])[]];\n'
(out/'molecule-library.generated.ts').write_text(header + record_type + 'export const MOLECULE_LIBRARY_DATA: readonly LibraryRecord[] = ' + json.dumps(records,ensure_ascii=False,separators=(',',':')) + ';\n')
ids = ['water','carbon-dioxide','methane','ammonia'] + [r[0] for r in records]
(out/'molecule-ids.generated.ts').write_text(header + 'export const MOLECULE_PRESET_IDS = ' + json.dumps(ids) + ' as const;\n')
manifest = {'retrieved':'2026-09-16','scope':'PubChem-generated numeric conformers and factual atom/bond graphs only. No third-party descriptions or imagery.', 'policy':'https://pubchem.ncbi.nlm.nih.gov/pcfe/docs/markdown/pubchem3d.md','records':provenance,'excluded':excluded}
(ROOT/'docs/previews/science/molecular-sources.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
print('IMPORTED',len(records),'EXCLUDED',len(excluded),flush=True)

# Electron configurations have their own NIST-first importer.
