"""Import factual ground-shell designations, preferring NIST ASD over PubChem.
Only configurations (no artwork/text, energies or isotope assumptions) are bundled.
NIST coverage 1–108; PubChem predicted configurations for 109–118.
"""
import csv
import hashlib
import json
import pathlib
import re
import urllib.request
import argparse

ROOT=pathlib.Path(__file__).resolve().parents[1]
pubchem='https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON'
nist='https://physics.nist.gov/cgi-bin/ASD/ie.pl?spectra=H-Og%20I&units=1&format=2&order=0&at_num_out=on&sp_name_out=on&ion_charge_out=on&el_name_out=on&shells_out=on&level_out=on&e_out=0'
def read(url):
    with urllib.request.urlopen(url,timeout=40) as response:
        return response.read()
parser=argparse.ArgumentParser()
parser.add_argument('--pubchem-json',type=pathlib.Path)
parser.add_argument('--nist-csv',type=pathlib.Path)
args=parser.parse_args()
p=args.pubchem_json.read_bytes() if args.pubchem_json else read(pubchem)
n=args.nist_csv.read_bytes() if args.nist_csv else read(nist)
configs={r['Cell'][1]:r['Cell'][5] for r in json.loads(p)['Table']['Row']}
sources={s:'PubChem (predicted)' for s in configs}
for row in csv.DictReader(n.decode().splitlines()):
    clean=lambda key:(row.get(key) or '').removeprefix('="').removesuffix('"')
    if not clean('At. num').isdigit():
        continue
    symbol=clean('Sp. Name').split()[0]
    config=clean('Ground Shells (a)').replace('.',' ')
    config=re.sub(r'([1-7][spdf])(?!\d)',r'\g<1>1',config)
    configs[symbol]=config+(' (predicted)' if int(clean('At. num'))>=104 else '')
    sources[symbol]='NIST ASD'
out=ROOT/'packages/core/src/objects/electron-configurations.generated.ts'
out.write_text('// Generated by scripts/import-electron-configurations.py; factual neutral configurations.\nexport const ELECTRON_CONFIGURATIONS: Readonly<Record<string,string>> = '+json.dumps(configs,separators=(',',':'))+';\n')
manifest={'retrieved':'2026-09-16','scope':'Neutral reference configurations; Z≥104 labelled theoretical. No ionic or isotope data inferred. NIST Lr is 7p1, not the older PubChem 6d1 entry.','sources':[{'url':nist,'sha256':hashlib.sha256(n).hexdigest(),'elements':108},{'url':pubchem,'sha256':hashlib.sha256(p).hexdigest(),'elements':10}],'perElement':sources}
(ROOT/'docs/previews/science/electron-configuration-source.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Configurations:',len(configs))
