import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {MaterialObject} from "../packages/core/src/objects/MaterialObject";
import {MATERIAL_IDS,MATERIAL_NAMES,type MaterialId,type MaterialStyle} from "../packages/core/src/objects/materials";
function Preview(){const [id,setId]=useState<MaterialId>("material-crystal"),[style,setStyle]=useState<MaterialStyle>("photorealistic"),[playing,setPlaying]=useState(true),[dark,setDark]=useState(true),[size,setSize]=useState(420),[speed,setSpeed]=useState(1);
return <main style={{fontFamily:"system-ui",background:dark?"#070b16":"#f5f1e9",color:dark?"#eff8ff":"#252338",minHeight:"180vh",padding:24}}><h1>Cristaux & matières</h1><p>Croissance, fusion, pli ou fissuration locale. Une lumière secondaire au maximum. Vignettes fixes.</p>
<div style={{display:"flex",gap:12,flexWrap:"wrap"}}><label>Objet <select value={id} onChange={e=>setId(e.target.value as MaterialId)}>{MATERIAL_IDS.map(i=><option key={i} value={i}>{MATERIAL_NAMES[i].fr}</option>)}</select></label><label>Style <select value={style} onChange={e=>setStyle(e.target.value as MaterialStyle)}><option value="photorealistic">Matière studio</option><option value="illustration">Illustration</option></select></label><button onClick={()=>setPlaying(!playing)}>{playing?"Pause":"Reprendre"}</button><button onClick={()=>setDark(!dark)}>Fond {dark?"clair":"sombre"}</button><label>Format <select value={size} onChange={e=>setSize(+e.target.value)}><option value="420">420 px</option><option value="160">160 px</option></select></label><label>Vitesse <select value={speed} onChange={e=>setSpeed(+e.target.value)}><option value=".5">× 0,5</option><option value="1">× 1</option><option value="2">× 2</option></select></label></div>
<MaterialObject id={id} label={MATERIAL_NAMES[id].fr} style={style} size={size} playing={playing} speed={speed}/><div style={{display:"flex",flexWrap:"wrap"}}>{MATERIAL_IDS.map(i=><button key={i} onClick={()=>setId(i)} style={{background:"transparent",color:"inherit",border:"1px solid #8191a355",borderRadius:12,margin:5}}><MaterialObject id={i} label={MATERIAL_NAMES[i].fr} style={style} size={120} thumbnail/><div>{MATERIAL_NAMES[i].fr}</div></button>)}</div><p>Faire défiler vérifie l’arrêt hors écran. Les préférences reduced motion figent la scène.</p></main>}
createRoot(document.getElementById("root")!).render(<Preview/>);
