// Chaînes d'interface (chrome) bilingues FR/EN pour le module Gestion de parc / Asset Manager.
// IMPORTANT : seul le "chrome" est traduit ici. Les données métier (labels de config
// domain.*.json, statuts d'API, valeurs Prisma, ids techniques) NE sont PAS traduites.
//
// Pattern : `const fr = {...};` SANS `as const` (sinon typeof fr se fige sur les
// littéraux FR et `en` ne compile pas), puis `const en: typeof fr = {...};`.

const fr = {
  // Commun à tout le module
  common: {
    moduleTitle: "Gestion de parc",
    breadcrumbModules: "Modules",
    loading: "Chargement…",
    back: "Retour",
    backToModules: "← Retour aux modules",
    backToModule: "← Retour au module",
    cancel: "Annuler",
    save: "Enregistrer",
    saving: "Enregistrement…",
    create: "Créer",
    creating: "Création…",
    edit: "Modifier",
    delete: "Supprimer",
    deleting: "Suppression…",
    confirm: "Confirmer",
    search: "Rechercher",
    searchPlaceholder: "Rechercher…",
    exportCsv: "Exporter CSV",
    all: "Tous",
    none: "Aucun",
    yes: "Oui",
    no: "Non",
    required: "obligatoire",
    optional: "facultatif",
    actions: "Actions",
    status: "Statut",
    priority: "Priorité",
    type: "Type",
    label: "Libellé",
    reference: "Référence",
    description: "Description",
    notFound: "Introuvable",
    errorGeneric: "Une erreur est survenue.",
    retry: "Réessayer",
    dash: "—",
  },

  // Navigation (sidebar + onglets mobiles)
  nav: {
    dashboard: "Tableau de bord",
    assets: "Équipements",
    tickets: "Tickets",
    assignments: "Mise à disposition",
    contracts: "Contrats",
    knowledge: "Connaissances",
    changes: "Changements",
    cmdb: "Cartographie CMDB",
    audit: "Journal d'audit",
    ariaLabel: "Navigation Gestion de parc",
  },

  // Page de redirection / sélection de domaine + hub
  hub: {
    noConfigDescription: "Aucune configuration de domaine disponible.",
    configRequiredTitle: "Configuration requise",
    noDomainConfiguredPrefix: "Aucun domaine n'est configuré. Vérifiez les fichiers ",
    authRequiredTitle: "Connexion requise",
    authRequiredDescription: "Cette démonstration nécessite une session. Connectez-vous pour accéder à la gestion de parc.",
    loginCta: "Se connecter",
    configNotFoundTitle: "Configuration introuvable",
    domainNotConfigured: (domainId: string) => (
      `Le domaine "${domainId}" n'existe pas ou n'est pas configuré.`
    ),
    newAsset: "+ Nouvel actif",
    scrollLeft: "Défiler vers la gauche",
    scrollRight: "Défiler vers la droite",
    metricsAriaLabel: "Métriques du tableau de bord",
    alerts: "Alertes",
    contractsExpiring: (n: number) => `contrat(s) arrivant à échéance sous 30 jours`,
    ticketsSlaRisk: "ticket(s) en danger ou dépassement SLA",
    assetsOutOfService: "actif(s) hors service",
    cmdbButton: "Cartographie CMDB",
    noAssetsHint: "Aucun actif. Cliquez sur « Nouvel actif » pour en créer un.",
    noAssetRegistered: "Aucun actif enregistré",
    noTicket: "Aucun ticket",
    noAssignment: "Aucune MAD",
    noContract: "Aucun contrat",
    noArticle: "Aucun article",
    noChange: "Aucun changement",
    updatedAt: (date: string) => `Mise à jour : ${date}`,
    dashboardSubtitle: (assetsPlural: string, assignmentLabel: string) =>
      `${assetsPlural}, Tickets et ${assignmentLabel}s. Tableau de bord et accès rapides.`,
    colReference: "Référence",
    colLabel: "Libellé",
    colType: "Type",
    colStatus: "Statut",
    contracts: "Contrats",
    knowledge: "Connaissances",
    changes: "Changements",
  },

  // Feature : Équipements / Inventaire
  assets: {
    defaultTitle: "Équipements",
    listSubtitle: "Liste des actifs avec filtres par type et statut.",
    newAsset: "+ Nouvel actif",
    filters: "Filtres",
    filterType: "Type",
    filterStatus: "Statut",
    filterLifecycle: "Cycle de vie",
    allTypes: "Tous les types",
    allStatuses: "Tous les statuts",
    allStages: "Toutes les étapes",
    colReference: "Référence",
    colLabel: "Libellé",
    colType: "Type",
    colStatus: "Statut",
    colLifecycle: "Cycle de vie",
    exportCsv: "Exporter CSV",
    csvFilePrefix: "actifs",
    emptyTitle: "Aucun équipement enregistré",
    emptyDescription: "Créez un premier actif pour commencer à gérer votre parc.",
    // Création
    breadcrumbNew: "Nouveau",
    newAssetHeading: (singularLower: string) => `Nouvel ${singularLower}`,
    fillBelow: "Remplissez les informations ci-dessous.",
    sectionIdentification: "Identification",
    sectionCharacteristics: "Caractéristiques",
    fieldTypeRequired: "Type *",
    fieldLabelRequired: "Libellé *",
    fieldStatusRequired: "Statut *",
    fieldStatus: "Statut",
    chooseType: "Choisir le type",
    placeholderType: "Type",
    placeholderStatus: "Statut",
    placeholderAssetName: "Nom de l'actif",
    placeholderLabel: "Libellé",
    errRequiredAll: "Libellé, type et statut sont requis.",
    errRequiredLabel: "Le libellé est requis.",
    errCreate: "Erreur à la création.",
    errCreateGeneric: "Erreur lors de la création.",
    errNetwork: "Erreur réseau.",
    creating: "Création…",
    create: "Créer",
    cancel: "Annuler",
    backList: "← Liste des actifs",
    back: "← Retour",
    // Détail
    notFoundTitle: "Actif introuvable",
    notFoundDescription: "L'actif demandé n'existe pas ou vous n'y avez pas accès.",
    defaultPlural: "Actifs",
    sectionGeneral: "Informations générales",
    fieldReference: "Référence",
    fieldType: "Type",
    fieldStatusLabel: "Statut",
    fieldLifecycleStage: "Étape de cycle de vie",
    lifecycleUndefined: "— Non défini",
    choose: "Choisir",
    saving: "Enregistrement…",
    fieldBrand: "Marque",
    fieldModel: "Modèle",
    fieldSerial: "N° série",
    sectionMovements: "Historique des mouvements",
    metricMovements: "Mouvements",
    addMovement: "+ Ajouter un mouvement",
    newMovement: "Nouveau mouvement",
    fieldDate: "Date",
    fieldReasonOptional: "Raison (optionnel)",
    placeholderReason: "Ex. Affectation bureau 101",
    fieldNotesOptional: "Notes (optionnel)",
    placeholderComment: "Commentaire",
    saveMovement: "Enregistrer le mouvement",
    emptyMovementsTitle: "Aucun mouvement",
    emptyMovementsDescription: "Aucun mouvement enregistré.",
    sectionTickets: "Tickets",
    emptyTicketsTitle: "Aucun ticket",
    emptyTicketsDescription: "Aucun ticket lié à cet actif.",
    newTicket: "+ Nouveau ticket",
    sectionContracts: "Contrats",
    emptyContractsTitle: "Aucun contrat",
    emptyContractsDescription: "Aucun contrat couvrant cet actif.",
    contractEnd: (date: string) => `Fin : ${date}`,
    sectionDependencies: "Dépendances / Cartographie",
    metricRelations: "Relations",
    addRelation: "+ Ajouter une relation",
    fieldTargetAsset: "Actif cible",
    chooseAsset: "Choisir un actif",
    fieldRelationType: "Type de relation",
    add: "Ajouter",
    emptyRelationsTitle: "Aucune relation",
    emptyRelationsDescription: "Ajoutez une dépendance ou un lien.",
    delete: "Supprimer",
    confirmDeleteRelation: "Supprimer cette relation ?",
    sectionNotes: "Notes",
    yes: "Oui",
    no: "Non",
    movementTypes: {
      reception: "Réception",
      deployment: "Déploiement",
      transfer: "Transfert",
      return: "Retour",
      repair_out: "Sortie réparation",
      repair_in: "Retour réparation",
      disposal: "Réforme",
    } as Record<string, string>,
    relationTypes: {
      depends_on: "Dépend de",
      connected_to: "Connecté à",
      hosted_on: "Hébergé sur",
      fed_by: "Alimenté par",
      controls: "Contrôle",
    } as Record<string, string>,
    lifecycleStages: {
      achat: "Achat",
      reception: "Réception",
      deploiement: "Déploiement",
      en_service: "En service",
      maintenance: "Maintenance",
      renouvellement: "Renouvellement",
      reforme: "Réforme",
    } as Record<string, string>,
  },
};

const en: typeof fr = {
  common: {
    moduleTitle: "Asset Management",
    breadcrumbModules: "Modules",
    loading: "Loading…",
    back: "Back",
    backToModules: "← Back to modules",
    backToModule: "← Back to module",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    create: "Create",
    creating: "Creating…",
    edit: "Edit",
    delete: "Delete",
    deleting: "Deleting…",
    confirm: "Confirm",
    search: "Search",
    searchPlaceholder: "Search…",
    exportCsv: "Export CSV",
    all: "All",
    none: "None",
    yes: "Yes",
    no: "No",
    required: "required",
    optional: "optional",
    actions: "Actions",
    status: "Status",
    priority: "Priority",
    type: "Type",
    label: "Label",
    reference: "Reference",
    description: "Description",
    notFound: "Not found",
    errorGeneric: "An error occurred.",
    retry: "Retry",
    dash: "—",
  },

  nav: {
    dashboard: "Dashboard",
    assets: "Inventory",
    tickets: "Tickets",
    assignments: "Assignments",
    contracts: "Contracts",
    knowledge: "Knowledge",
    changes: "Changes",
    cmdb: "CMDB Map",
    audit: "Audit log",
    ariaLabel: "Asset Management navigation",
  },

  hub: {
    noConfigDescription: "No domain configuration available.",
    configRequiredTitle: "Configuration required",
    noDomainConfiguredPrefix: "No domain is configured. Check the ",
    authRequiredTitle: "Sign-in required",
    authRequiredDescription: "This demo requires a session. Sign in to access asset management.",
    loginCta: "Sign in",
    configNotFoundTitle: "Configuration not found",
    domainNotConfigured: (domainId: string) => (
      `Domain "${domainId}" does not exist or is not configured.`
    ),
    newAsset: "+ New asset",
    scrollLeft: "Scroll left",
    scrollRight: "Scroll right",
    metricsAriaLabel: "Dashboard metrics",
    alerts: "Alerts",
    contractsExpiring: (n: number) => `contract(s) expiring within 30 days`,
    ticketsSlaRisk: "ticket(s) at risk or past SLA",
    assetsOutOfService: "out-of-service asset(s)",
    cmdbButton: "CMDB Map",
    noAssetsHint: "No assets. Click “New asset” to create one.",
    noAssetRegistered: "No asset registered",
    noTicket: "No ticket",
    noAssignment: "No assignment",
    noContract: "No contract",
    noArticle: "No article",
    noChange: "No change",
    updatedAt: (date: string) => `Updated: ${date}`,
    dashboardSubtitle: (assetsPlural: string, assignmentLabel: string) =>
      `${assetsPlural}, Tickets and ${assignmentLabel}s. Dashboard and quick access.`,
    colReference: "Reference",
    colLabel: "Label",
    colType: "Type",
    colStatus: "Status",
    contracts: "Contracts",
    knowledge: "Knowledge",
    changes: "Changes",
  },

  assets: {
    defaultTitle: "Inventory",
    listSubtitle: "List of assets with filters by type and status.",
    newAsset: "+ New asset",
    filters: "Filters",
    filterType: "Type",
    filterStatus: "Status",
    filterLifecycle: "Lifecycle",
    allTypes: "All types",
    allStatuses: "All statuses",
    allStages: "All stages",
    colReference: "Reference",
    colLabel: "Label",
    colType: "Type",
    colStatus: "Status",
    colLifecycle: "Lifecycle",
    exportCsv: "Export CSV",
    csvFilePrefix: "assets",
    emptyTitle: "No asset registered",
    emptyDescription: "Create your first asset to start managing your inventory.",
    breadcrumbNew: "New",
    newAssetHeading: (singularLower: string) => `New ${singularLower}`,
    fillBelow: "Fill in the information below.",
    sectionIdentification: "Identification",
    sectionCharacteristics: "Characteristics",
    fieldTypeRequired: "Type *",
    fieldLabelRequired: "Label *",
    fieldStatusRequired: "Status *",
    fieldStatus: "Status",
    chooseType: "Choose the type",
    placeholderType: "Type",
    placeholderStatus: "Status",
    placeholderAssetName: "Asset name",
    placeholderLabel: "Label",
    errRequiredAll: "Label, type and status are required.",
    errRequiredLabel: "Label is required.",
    errCreate: "Error while creating.",
    errCreateGeneric: "Error while creating.",
    errNetwork: "Network error.",
    creating: "Creating…",
    create: "Create",
    cancel: "Cancel",
    backList: "← Asset list",
    back: "← Back",
    notFoundTitle: "Asset not found",
    notFoundDescription: "The requested asset does not exist or you don't have access to it.",
    defaultPlural: "Assets",
    sectionGeneral: "General information",
    fieldReference: "Reference",
    fieldType: "Type",
    fieldStatusLabel: "Status",
    fieldLifecycleStage: "Lifecycle stage",
    lifecycleUndefined: "— Not set",
    choose: "Choose",
    saving: "Saving…",
    fieldBrand: "Brand",
    fieldModel: "Model",
    fieldSerial: "Serial no.",
    sectionMovements: "Movement history",
    metricMovements: "Movements",
    addMovement: "+ Add a movement",
    newMovement: "New movement",
    fieldDate: "Date",
    fieldReasonOptional: "Reason (optional)",
    placeholderReason: "e.g. Assigned to office 101",
    fieldNotesOptional: "Notes (optional)",
    placeholderComment: "Comment",
    saveMovement: "Save movement",
    emptyMovementsTitle: "No movement",
    emptyMovementsDescription: "No movement recorded.",
    sectionTickets: "Tickets",
    emptyTicketsTitle: "No ticket",
    emptyTicketsDescription: "No ticket linked to this asset.",
    newTicket: "+ New ticket",
    sectionContracts: "Contracts",
    emptyContractsTitle: "No contract",
    emptyContractsDescription: "No contract covering this asset.",
    contractEnd: (date: string) => `End: ${date}`,
    sectionDependencies: "Dependencies / Map",
    metricRelations: "Relations",
    addRelation: "+ Add a relation",
    fieldTargetAsset: "Target asset",
    chooseAsset: "Choose an asset",
    fieldRelationType: "Relation type",
    add: "Add",
    emptyRelationsTitle: "No relation",
    emptyRelationsDescription: "Add a dependency or a link.",
    delete: "Delete",
    confirmDeleteRelation: "Delete this relation?",
    sectionNotes: "Notes",
    yes: "Yes",
    no: "No",
    movementTypes: {
      reception: "Reception",
      deployment: "Deployment",
      transfer: "Transfer",
      return: "Return",
      repair_out: "Sent for repair",
      repair_in: "Back from repair",
      disposal: "Disposal",
    } as Record<string, string>,
    relationTypes: {
      depends_on: "Depends on",
      connected_to: "Connected to",
      hosted_on: "Hosted on",
      fed_by: "Fed by",
      controls: "Controls",
    } as Record<string, string>,
    lifecycleStages: {
      achat: "Purchase",
      reception: "Reception",
      deploiement: "Deployment",
      en_service: "In service",
      maintenance: "Maintenance",
      renouvellement: "Renewal",
      reforme: "Disposal",
    } as Record<string, string>,
  },
};

// Sections additionnelles fusionnées (tickets, assignments, contracts, changes,
// knowledge, audit, cmdb, documentation). Définies hors des objets fr/en pour
// éviter les conflits d'édition ; la parité de type est garantie via mergeStr.
import { extraFr, extraEn } from "./strings.extra";

const frFull = { ...fr, ...extraFr };
const enFull: typeof frFull = { ...en, ...extraEn };

export const STR = { fr: frFull, en: enFull };

export type AssetManagerStrings = typeof frFull;

/** Locale de date associée. */
export function dateLocale(locale: "fr" | "en"): string {
  return locale === "en" ? "en-US" : "fr-FR";
}
