// Sections de chrome supplémentaires pour le module Gestion de parc / Asset Manager.
// Même règle de parité : `extraFr` SANS `as const`, puis `extraEn: typeof extraFr`.
// Seul le chrome est traduit ; les données métier (config, API, Prisma) restent inchangées.

const extraFr = {
  tickets: {
    title: "Tickets",
    listSubtitle: "Liste des tickets avec filtres par statut et priorité.",
    newTicket: "Nouveau ticket",
    filters: "Filtres",
    filterStatus: "Statut",
    filterPriority: "Priorité",
    filterSla: "SLA",
    allStatuses: "Tous les statuts",
    allPriorities: "Toutes les priorités",
    colReference: "Référence",
    colTitle: "Titre",
    colStatus: "Statut",
    colPriority: "Priorité",
    colCategory: "Catégorie",
    colOpenedAt: "Ouvert le",
    colAssignee: "Assigné à",
    emptyTitle: "Aucun ticket",
    emptyDescription: "Aucun ticket pour ce domaine. Créez-en un pour commencer.",
    csvFilePrefix: "tickets",
    checkUrl: "Vérifiez l'URL du domaine.",
    breadcrumbDashboard: "Tableau de bord",
    breadcrumbTickets: "Tickets",
    breadcrumbNew: "Nouveau",
    fillBelow: "Remplissez les informations ci-dessous.",
    sectionRequest: "Demande",
    fieldTitle: "Titre",
    placeholderTitle: "Résumé du problème ou de la demande",
    fieldDescriptionRequired: "Description *",
    placeholderDescription: "Décrivez le problème ou la demande...",
    sectionClassification: "Classification",
    fieldType: "Type",
    fieldPriority: "Priorité",
    fieldCategory: "Catégorie",
    fieldSubcategory: "Sous-catégorie",
    fieldRelatedAsset: "Actif concerné",
    optionNone: "— Aucun",
    sectionHelp: "Aide",
    suggestedArticles: "Articles susceptibles de vous aider",
    createTicket: "Créer le ticket",
    backToList: "← Liste des tickets",
    notFoundTitle: "Ticket introuvable",
    notFoundDescription: "Ce ticket n'existe pas ou vous n'y avez pas accès.",
    slaTitle: "SLA",
    slaExceeded: "SLA dépassé",
    slaOk: "SLA OK",
    sectionInformation: "Informations",
    fieldRequester: "Demandeur",
    fieldAssignee: "Assigné à",
    fieldLinkedAsset: "Actif lié",
    sectionKnowledge: "Connaissances",
    knowledgeHint: "Créez un article à partir de ce ticket pour enrichir les connaissances.",
    publishKnowledge: "Publier en connaissances",
    editTicket: "Modifier le ticket",
    fieldSolution: "Solution (si résolu)",
    placeholderSolution: "Décrire la solution...",
    slaRiskChip: (n: number) => `${n} en danger SLA`,
    openedOn: (date: string) => `Ouvert le ${date}`,
    slaConsumed: (slaHours: number) => `Temps consommé (objectif : ${slaHours} h)`,
    statusLabels: {
      new: "Nouveau",
      open: "Ouvert",
      pending: "En attente",
      in_progress: "En cours",
      on_hold: "En attente",
      assigned: "Assigné",
      resolved: "Résolu",
      closed: "Clos",
    } as Record<string, string>,
  },
  audit: {
    title: "Journal d'audit",
    description: "Historique des actions effectuées sur les actifs, tickets et changements.",
    domainRequired: "Domaine requis",
    filters: "Filtres",
    filterResourceType: "Type d'entité",
    filterAction: "Action",
    allTypes: "Tous les types",
    allActions: "Toutes les actions",
    colDate: "Date",
    colUser: "Utilisateur",
    colAction: "Action",
    colResource: "Entité",
    colDetail: "Détails",
    emptyTitle: "Aucune entrée d'audit",
    emptyDescription: "Aucune action enregistrée pour ce domaine.",
    backToDashboard: "← Tableau de bord",
    actionLabels: {
      create: "Création",
      update: "Modification",
      delete: "Suppression",
    } as Record<string, string>,
    resourceLabels: {
      asset: "Actif",
      ticket: "Ticket",
      change: "Changement",
      assignment: "Mise à disposition",
      contract: "Contrat",
      relation: "Relation",
    } as Record<string, string>,
  },
  cmdb: {
    title: "Cartographie CMDB",
    description: "Graphe des actifs et de leurs relations. Clic sur un nœud pour ouvrir la fiche actif.",
    domainRequired: "Domaine requis",
    assetList: "Liste des actifs",
    emptyTitle: "Aucun actif",
    emptyDescription: "Aucun actif dans ce domaine. Créez des actifs et des relations depuis les fiches actifs.",
    graphAriaLabel: "Graphe des dépendances",
    graphHeading: "Graphe des dépendances",
    backToDashboard: "← Tableau de bord",
    counts: (nodes: number, relations: number) => `${nodes} actif(s), ${relations} relation(s)`,
    relationLabels: {
      depends_on: "Dépend de",
      connected_to: "Connecté à",
      hosted_on: "Hébergé sur",
      fed_by: "Alimenté par",
      controls: "Contrôle",
    } as Record<string, string>,
  },
  documentation: {
    breadcrumbDocumentation: "Documentation",
    title: "Documentation — Gestion de parc",
    intro: "Module de gestion de parc : actifs, tickets et mise à disposition. Tableau de bord, équipements, tickets, mise à Disposition, contrats, connaissances et changements.",
    uxHeading: "Interface et UX",
    domainConfigHeading: "Configuration de domaine",
    apiHeading: "API",
    itsmHeading: "Compléments ITSM (Phase 2 et 3)",
    databaseHeading: "Base de données et prérequis production",
    newDomainHeading: "Créer un nouveau domaine",
    backToModule: "← Retour au module",
    uxPara1: "L'interface s'appuie sur le design system BPM avec une hiérarchie visuelle inspirée de Linear : fond de page ",
    uxPara2: ", cartes à bordure légère (12px, pas d'ombre marquée). En haut de chaque page : ",
    uxStrongBreadcrumb: "breadcrumb",
    uxPara3: " (Modules › Gestion de parc › …), ",
    uxStrongTabs: "onglets horizontaux",
    uxPara4: " (bpm.tabs) pour naviguer entre Tableau de bord, Équipements, Tickets, Mise à disposition, Contrats, Connaissances, Changements. Le bouton d'action principal (« Nouvel actif », « Nouveau ticket », etc.) est aligné à droite du titre (hauteur 40px). Les ",
    uxStrongFilters: "filtres",
    uxPara5: " sont des chips sélectionnables (32px, border-radius 6px, état actif bleu clair) avec défilement horizontal sur mobile ; l'export CSV est en bouton icône à droite. Les tableaux ont des en-têtes en semi-bold (font-weight 500, pas de majuscules), un hover sur les lignes (#F8F9FA) et des badges colorés pour Statut et Priorité. L'",
    uxStrongEmpty: "état vide",
    uxPara6: " est centré avec icône, titre, description et CTA (sans bpm.panel info). Le ",
    uxStrongDashboard: "tableau de bord",
    uxPara7: " affiche des cartes métriques compactes (bpm.metric) avec icône et couleur d'accent par domaine (bleu équipements, orange tickets, violet MAD, vert contrats, cyan base de connaissances, rose changements) et une micro-info sous chaque métrique.",
    configPara1: "Le module ne code pas en dur les types d'actifs. Il s'appuie sur un ",
    configStrongFile: "fichier de configuration JSON",
    configPara2: " qui décrit les types d'actifs, leurs champs, les statuts, les catégories de tickets, les priorités et les règles de numérotation.",
    domainConfigPara1: "Les configs sont dans ",
    domainConfigPara2: " : ",
    domainConfigPara3: ". Le schéma décrit ",
    domainConfigPara4: "(id, label, icon, fields avec key, type, options…), ",
    domainConfigPara5: ".",
    apiConfigList: "Liste des domaines disponibles.",
    apiConfigDomain: "Configuration d'un domaine.",
    apiAssetsList: "Liste des actifs (filtres optionnels : assetTypeId, statusId, search).",
    apiAssetsCreate: "Création d'un actif (body : domainId, assetTypeId, label, statusId, attributs…).",
    apiAssetsDetail: "Détail d'un actif.",
    apiAssetsUpdate: "Mise à jour.",
    apiAssetsDelete: "Suppression.",
    itsmPara1: "Cycle de vie des actifs, contrats et garanties, mouvements physiques, escalade SLA, connaissances, gestion des changements (CAB), CMDB (graphe de dépendances), RBAC et audit trail sont décrits dans ",
    itsmPara2: ". Les modèles Prisma correspondants (AssetContract, AssetMovement, KnowledgeArticle, ChangeRequest, CIRelation, AuditLog, Permission) sont définis dans le schéma et une migration est fournie ",
    itsmPara3: ".",
    databasePara1: "Le module utilise les tables ",
    databasePara2: ", plus la config ",
    databasePara3: ". Pour le détail des structures et variables d'environnement, voir ",
    databasePara4: " dans le dépôt.",
    newDomainPara1: "Dupliquez ",
    newDomainPara2: " en ",
    newDomainPara3: ", adaptez ",
    newDomainPara4: ", labels, ",
    newDomainPara5: "et ",
    newDomainPara6: ". Enregistrez le nouvel id dans ",
    newDomainPara7: ".",
  },
  changes: {
    title: "Changements",
    listSubtitle: "Liste des demandes de changement avec leur statut et niveau de risque.",
    breadcrumbDashboard: "Tableau de bord",
    breadcrumbChanges: "Changements",
    breadcrumbNew: "Nouveau",
    breadcrumbCalendar: "Calendrier",
    calendar: "Calendrier",
    newChange: "Nouveau changement",
    filters: "Filtres",
    filterStatus: "Statut",
    allStatuses: "Tous les statuts",
    colReference: "Référence",
    colTitle: "Titre",
    colType: "Type",
    colStatus: "Statut",
    colRisk: "Risque",
    colPlannedStart: "Début prévu",
    csvFilePrefix: "changements",
    emptyTitle: "Aucune demande de changement",
    emptyDescription: "Créez une première demande de changement pour commencer.",
    documentation: "Documentation",
    checkUrl: "Vérifiez l'URL ou la configuration du domaine.",
    newPageTitle: "Nouvelle demande de changement",
    fillBelow: "Remplissez les informations ci-dessous.",
    sectionTypeRisk: "Type et risque",
    sectionPlanning: "Planification",
    sectionRollback: "Plan de rollback",
    rollbackPlanAria: "Plan de rollback",
    fieldRiskLevelRequired: "Niveau de risque *",
    fieldTitleRequired: "Titre *",
    placeholderTitle: "Titre court de la demande",
    fieldDescriptionRequired: "Description *",
    fieldImpactRequired: "Impact *",
    fieldPlannedStart: "Début prévu",
    fieldPlannedEnd: "Fin prévue",
    fieldRollbackPlanRequired: "Plan de rollback *",
    createChange: "Créer la demande",
    backToChanges: "← Changements",
    notFoundTitle: "Demande introuvable",
    notFoundDescription: "Cette demande n'existe pas ou vous n'y avez pas accès.",
    submitToCabTitle: "Soumettre au CAB",
    submitToCabDescription: "Envoyer cette demande en revue CAB pour approbation.",
    submitToCab: "Soumettre au CAB",
    cabReviewTitle: "Revue CAB",
    cabReviewDescription: "Approuvez ou rejetez cette demande de changement.",
    inProgress: "En cours…",
    approve: "Approuver",
    reject: "Rejeter",
    rejectCommentLabel: "Commentaire de rejet (optionnel)",
    rejectCommentPlaceholder: "Motif du rejet...",
    requestDetailTitle: "Détail de la demande",
    fieldDates: "Dates",
    fieldImpact: "Impact",
    fieldRollbackPlan: "Plan de rollback",
    rollbackNotSet: "— Non renseigné",
    domainRequired: "Domaine requis",
    calendarTitle: "Calendrier des changements",
    calendarSubtitle: "Changements avec date de début prévue.",
    monthlyView: "Vue mensuelle",
    backToChangesList: "← Liste des changements",
    cabPendingChip: (n: number) => `${n} en attente CAB`,
    plannedStartLabel: (date: string) => `Début prévu : ${date}`,
    plannedEndLabel: (date: string) => `Fin prévue : ${date}`,
    createdAt: (date: string) => `Créé le ${date}`,
    updatedAt: (date: string) => `Modifié le ${date}`,
    typeLabels: {
      standard: "Standard",
      normal: "Normal",
      emergency: "Urgent",
    } as Record<string, string>,
    statusLabels: {
      draft: "Brouillon",
      submitted: "Soumis",
      cab_review: "Revue CAB",
      approved: "Approuvé",
      rejected: "Rejeté",
      scheduled: "Planifié",
      in_progress: "En cours",
      completed: "Terminé",
      failed: "Échoué",
      cancelled: "Annulé",
    } as Record<string, string>,
    riskLabels: {
      low: "Faible",
      medium: "Moyen",
      high: "Élevé",
      critical: "Critique",
    } as Record<string, string>,
  },
  knowledge: {
    title: "Connaissances",
    listSubtitle: "Base de connaissances : procédures, FAQ et guides.",
    newArticle: "Nouvel article",
    filters: "Filtres",
    filterCategory: "Catégorie",
    allCategories: "Toutes les catégories",
    documentation: "Documentation →",
    checkUrl: "Vérifiez l'URL du domaine.",
    colTitle: "Titre",
    colCategory: "Catégorie",
    colTags: "Tags",
    colVisibility: "Visibilité",
    colPublishedAt: "Publié le",
    colViews: "Vues",
    draft: "Brouillon",
    visibilityPublic: "Public",
    visibilityTechniciansOnly: "Techniciens uniquement",
    visibilityTechniciansShort: "Techniciens",
    emptyTitle: "Aucun article",
    emptyDescription: "Créez un premier article pour démarrer votre base de connaissances.",
    breadcrumbNew: "Nouveau",
    newArticleHeading: "Nouvel article",
    prefilledFromTicket: "Pré-rempli depuis un ticket. Complétez puis créez l'article.",
    fillBelow: "Remplissez les informations ci-dessous.",
    sectionArticle: "Article",
    sectionMetadata: "Métadonnées",
    fieldTitleRequired: "Titre *",
    fieldContentRequired: "Contenu *",
    fieldCategory: "Catégorie",
    fieldAssetTypeOptional: "Type d'actif (optionnel)",
    fieldTags: "Tags (séparés par des virgules)",
    fieldVisibility: "Visibilité",
    placeholderTitle: "Titre de l'article",
    placeholderContent: "Contenu en Markdown ou texte...",
    placeholderTags: "ex: imprimante, erreur, papier",
    createArticle: "Créer l'article",
    creating: "Création…",
    notFoundTitle: "Article introuvable",
    notFoundDescription: "Cet article n'existe pas ou vous n'y avez pas accès.",
    metricViews: "Vues",
    metricHelpful: "Utile",
    metricNotHelpful: "Pas utile",
    sectionContent: "Contenu",
    editArticleHeading: "Modifier l'article",
    editPanelTitle: "Édition",
    backToArticle: "Retour à l'article",
    publishedOn: (date: string) => `Publié le ${date}`,
    categoryLabels: {
      procedure: "Procédure",
      faq: "FAQ",
      guide: "Guide",
      reference: "Référence",
      troubleshooting: "Dépannage",
    } as Record<string, string>,
  },
  contracts: {
    listTitle: "Contrats",
    listSubtitle: "Liste des contrats avec filtres par type.",
    newContract: "Nouveau contrat",
    filters: "Filtres",
    allTypes: "Tous les types",
    colReference: "Référence",
    colLabel: "Libellé",
    colType: "Type",
    colSupplier: "Fournisseur",
    colStart: "Début",
    colEnd: "Fin",
    colAmount: "Montant (€)",
    csvFilePrefix: "contrats",
    emptyTitle: "Aucun contrat enregistré",
    emptyDescription: "Créez un premier contrat pour suivre garanties, maintenances et échéances.",
    checkUrl: "Vérifiez l'URL du domaine.",
    documentation: "Documentation",
    breadcrumbNew: "Nouveau",
    fillBelow: "Remplissez les informations ci-dessous.",
    sectionIdentification: "Identification",
    sectionPeriod: "Période",
    sectionCoveredAssets: "Actifs couverts",
    sectionNotes: "Notes",
    fieldReferenceRequired: "Référence *",
    fieldLabelRequired: "Libellé *",
    fieldTypeRequired: "Type *",
    fieldStartRequired: "Début *",
    fieldEndRequired: "Fin *",
    fieldSupplier: "Fournisseur",
    fieldAmount: "Montant (€)",
    fieldNoticeDays: "Préavis (jours)",
    fieldAutoRenewal: "Renouvellement automatique",
    fieldAutoRenewalShort: "Renouvellement auto",
    placeholderReference: "Ex. GAR-2025-001",
    placeholderLabel: "Ex. Garantie constructeur",
    placeholderAmount: "Montant",
    placeholderNotesOptional: "Notes optionnelles",
    createContract: "Créer le contrat",
    backList: "← Liste des contrats",
    notFoundTitle: "Contrat introuvable",
    notFoundDescription: "Ce contrat n'existe pas ou vous n'y avez pas accès.",
    detailTitle: "Détail du contrat",
    fieldReference: "Référence",
    fieldType: "Type",
    fieldLabel: "Libellé",
    fieldStart: "Début",
    fieldEnd: "Fin",
    assetsSelected: (n: number) => `${n} actif(s) sélectionné(s)`,
    typeLabels: {
      garantie: "Garantie",
      maintenance: "Maintenance",
      leasing: "Leasing",
      credit_bail: "Crédit-bail",
      licence: "Licence",
    } as Record<string, string>,
  },
  assignments: {
    listTitle: "Mises à disposition",
    listDescription: "Suivez les actifs mis à disposition des bénéficiaires.",
    newCta: "Nouvelle affectation",
    filters: "Filtres",
    filterAllStatuses: "Tous les statuts",
    columnAsset: "Actif",
    columnAssignee: "Bénéficiaire",
    columnStart: "Début",
    columnExpectedEnd: "Fin prévue",
    statusActive: "En cours",
    statusReturned: "Retourné",
    statusOverdue: "En retard",
    statusCancelled: "Annulé",
    emptyTitle: "Aucune affectation",
    emptyDescription: "Créez une première mise à disposition pour commencer.",
    breadcrumbDashboard: "Tableau de bord",
    breadcrumbShort: "MAD",
    breadcrumbNew: "Nouvelle",
    newTitle: "Nouvelle mise à disposition",
    newCaption: "Affectez un actif à un bénéficiaire.",
    sectionAssignment: "Affectation",
    sectionPeriod: "Période",
    sectionReason: "Motif",
    fieldAssetRequired: "Actif *",
    selectAssetPlaceholder: "Sélectionner un actif",
    fieldAssignee: "Bénéficiaire",
    assigneeSelfFallback: "Vous",
    typeTemporary: "Temporaire",
    typePermanent: "Permanent",
    fieldStartDateRequired: "Date de début *",
    fieldExpectedEndDate: "Date de fin prévue",
    fieldReasonOptional: "Motif (facultatif)",
    creating: "Création…",
    createCta: "Créer la MAD",
    backToList: "← Liste des MAD",
    notFoundTitle: "Mise à disposition introuvable",
    notFoundBody: "Cette MAD n'existe pas ou vous n'y avez pas accès.",
    beneficiaryLabel: "Bénéficiaire :",
    returnTitle: "Restituer l'actif",
    returnDescription: "Clôture la MAD, enregistre la date de retour et remet l'actif en stock.",
    returnCta: "Restituer l'actif",
    returning: "En cours…",
    returnConfirm: "Clôturer cette mise à disposition et remettre l'actif en stock ?",
    sectionInfo: "Informations",
    fieldAsset: "Actif",
    fieldBeneficiary: "Bénéficiaire",
    fieldStart: "Début",
    fieldExpectedEnd: "Fin prévue",
    fieldActualEnd: "Fin réelle",
    fieldLinkedTicket: "Ticket lié",
    fieldReason: "Motif",
    editTitle: "Modifier",
    fieldConditionReturn: "État au retour",
    fieldContractSigned: "Contrat signé",
  },
};

const extraEn: typeof extraFr = {
  tickets: {
    title: "Tickets",
    listSubtitle: "List of tickets with filters by status and priority.",
    newTicket: "New ticket",
    filters: "Filters",
    filterStatus: "Status",
    filterPriority: "Priority",
    filterSla: "SLA",
    allStatuses: "All statuses",
    allPriorities: "All priorities",
    colReference: "Reference",
    colTitle: "Title",
    colStatus: "Status",
    colPriority: "Priority",
    colCategory: "Category",
    colOpenedAt: "Opened",
    colAssignee: "Assignee",
    emptyTitle: "No ticket",
    emptyDescription: "No ticket for this domain. Create one to get started.",
    csvFilePrefix: "tickets",
    checkUrl: "Check the domain URL.",
    breadcrumbDashboard: "Dashboard",
    breadcrumbTickets: "Tickets",
    breadcrumbNew: "New",
    fillBelow: "Fill in the information below.",
    sectionRequest: "Request",
    fieldTitle: "Title",
    placeholderTitle: "Summary of the issue or request",
    fieldDescriptionRequired: "Description *",
    placeholderDescription: "Describe the issue or request...",
    sectionClassification: "Classification",
    fieldType: "Type",
    fieldPriority: "Priority",
    fieldCategory: "Category",
    fieldSubcategory: "Subcategory",
    fieldRelatedAsset: "Related asset",
    optionNone: "— None",
    sectionHelp: "Help",
    suggestedArticles: "Articles that might help you",
    createTicket: "Create ticket",
    backToList: "← Ticket list",
    notFoundTitle: "Ticket not found",
    notFoundDescription: "This ticket does not exist or you don't have access to it.",
    slaTitle: "SLA",
    slaExceeded: "SLA exceeded",
    slaOk: "SLA OK",
    sectionInformation: "Information",
    fieldRequester: "Requester",
    fieldAssignee: "Assignee",
    fieldLinkedAsset: "Linked asset",
    sectionKnowledge: "Knowledge",
    knowledgeHint: "Create an article from this ticket to enrich the knowledge base.",
    publishKnowledge: "Publish to knowledge",
    editTicket: "Edit ticket",
    fieldSolution: "Solution (if resolved)",
    placeholderSolution: "Describe the solution...",
    slaRiskChip: (n: number) => `${n} at SLA risk`,
    openedOn: (date: string) => `Opened on ${date}`,
    slaConsumed: (slaHours: number) => `Time consumed (target: ${slaHours} h)`,
    statusLabels: {
      new: "New",
      open: "Open",
      pending: "Pending",
      in_progress: "In progress",
      on_hold: "On hold",
      assigned: "Assigned",
      resolved: "Resolved",
      closed: "Closed",
    } as Record<string, string>,
  },
  audit: {
    title: "Audit log",
    description: "History of actions performed on assets, tickets and changes.",
    domainRequired: "Domain required",
    filters: "Filters",
    filterResourceType: "Entity type",
    filterAction: "Action",
    allTypes: "All types",
    allActions: "All actions",
    colDate: "Date",
    colUser: "User",
    colAction: "Action",
    colResource: "Entity",
    colDetail: "Details",
    emptyTitle: "No audit entry",
    emptyDescription: "No action recorded for this domain.",
    backToDashboard: "← Dashboard",
    actionLabels: {
      create: "Creation",
      update: "Update",
      delete: "Deletion",
    } as Record<string, string>,
    resourceLabels: {
      asset: "Asset",
      ticket: "Ticket",
      change: "Change",
      assignment: "Assignment",
      contract: "Contract",
      relation: "Relation",
    } as Record<string, string>,
  },
  cmdb: {
    title: "CMDB Map",
    description: "Graph of assets and their relations. Click a node to open the asset record.",
    domainRequired: "Domain required",
    assetList: "Asset list",
    emptyTitle: "No asset",
    emptyDescription: "No asset in this domain. Create assets and relations from the asset records.",
    graphAriaLabel: "Dependency graph",
    graphHeading: "Dependency graph",
    backToDashboard: "← Dashboard",
    counts: (nodes: number, relations: number) => `${nodes} asset(s), ${relations} relation(s)`,
    relationLabels: {
      depends_on: "Depends on",
      connected_to: "Connected to",
      hosted_on: "Hosted on",
      fed_by: "Fed by",
      controls: "Controls",
    } as Record<string, string>,
  },
  documentation: {
    breadcrumbDocumentation: "Documentation",
    title: "Documentation — Asset Management",
    intro: "Asset management module: assets, tickets and assignments. Dashboard, equipment, tickets, assignments, contracts, knowledge and changes.",
    uxHeading: "Interface and UX",
    domainConfigHeading: "Domain configuration",
    apiHeading: "API",
    itsmHeading: "ITSM complements (Phase 2 and 3)",
    databaseHeading: "Database and production prerequisites",
    newDomainHeading: "Create a new domain",
    backToModule: "← Back to module",
    uxPara1: "The interface builds on the BPM design system with a visual hierarchy inspired by Linear: page background ",
    uxPara2: ", cards with a light border (12px, no heavy shadow). At the top of each page: ",
    uxStrongBreadcrumb: "breadcrumb",
    uxPara3: " (Modules › Asset Management › …), ",
    uxStrongTabs: "horizontal tabs",
    uxPara4: " (bpm.tabs) to navigate between Dashboard, Equipment, Tickets, Assignments, Contracts, Knowledge, Changes. The primary action button (\"New asset\", \"New ticket\", etc.) is aligned to the right of the title (40px height). The ",
    uxStrongFilters: "filters",
    uxPara5: " are selectable chips (32px, border-radius 6px, light-blue active state) with horizontal scrolling on mobile; CSV export is an icon button on the right. Tables have semi-bold headers (font-weight 500, no uppercase), a hover state on rows (#F8F9FA) and colored badges for Status and Priority. The ",
    uxStrongEmpty: "empty state",
    uxPara6: " is centered with an icon, title, description and CTA (without bpm.panel info). The ",
    uxStrongDashboard: "dashboard",
    uxPara7: " displays compact metric cards (bpm.metric) with an icon and an accent color per domain (blue equipment, orange tickets, purple assignments, green contracts, cyan knowledge base, pink changes) and a micro-info under each metric.",
    configPara1: "The module does not hard-code asset types. It relies on a ",
    configStrongFile: "JSON configuration file",
    configPara2: " that describes asset types, their fields, statuses, ticket categories, priorities and numbering rules.",
    domainConfigPara1: "The configs are in ",
    domainConfigPara2: ": ",
    domainConfigPara3: ". The schema describes ",
    domainConfigPara4: "(id, label, icon, fields with key, type, options…), ",
    domainConfigPara5: ".",
    apiConfigList: "List of available domains.",
    apiConfigDomain: "Configuration of a domain.",
    apiAssetsList: "List of assets (optional filters: assetTypeId, statusId, search).",
    apiAssetsCreate: "Create an asset (body: domainId, assetTypeId, label, statusId, attributes…).",
    apiAssetsDetail: "Asset details.",
    apiAssetsUpdate: "Update.",
    apiAssetsDelete: "Deletion.",
    itsmPara1: "Asset lifecycle, contracts and warranties, physical movements, SLA escalation, knowledge, change management (CAB), CMDB (dependency graph), RBAC and audit trail are described in ",
    itsmPara2: ". The corresponding Prisma models (AssetContract, AssetMovement, KnowledgeArticle, ChangeRequest, CIRelation, AuditLog, Permission) are defined in the schema and a migration is provided ",
    itsmPara3: ".",
    databasePara1: "The module uses the tables ",
    databasePara2: ", plus the config ",
    databasePara3: ". For the details of the structures and environment variables, see ",
    databasePara4: " in the repository.",
    newDomainPara1: "Duplicate ",
    newDomainPara2: " to ",
    newDomainPara3: ", adapt ",
    newDomainPara4: ", labels, ",
    newDomainPara5: "and ",
    newDomainPara6: ". Register the new id in ",
    newDomainPara7: ".",
  },
  changes: {
    title: "Changes",
    listSubtitle: "List of change requests with their status and risk level.",
    breadcrumbDashboard: "Dashboard",
    breadcrumbChanges: "Changes",
    breadcrumbNew: "New",
    breadcrumbCalendar: "Calendar",
    calendar: "Calendar",
    newChange: "New change",
    filters: "Filters",
    filterStatus: "Status",
    allStatuses: "All statuses",
    colReference: "Reference",
    colTitle: "Title",
    colType: "Type",
    colStatus: "Status",
    colRisk: "Risk",
    colPlannedStart: "Planned start",
    csvFilePrefix: "changes",
    emptyTitle: "No change request",
    emptyDescription: "Create your first change request to get started.",
    documentation: "Documentation",
    checkUrl: "Check the URL or the domain configuration.",
    newPageTitle: "New change request",
    fillBelow: "Fill in the information below.",
    sectionTypeRisk: "Type and risk",
    sectionPlanning: "Planning",
    sectionRollback: "Rollback plan",
    rollbackPlanAria: "Rollback plan",
    fieldRiskLevelRequired: "Risk level *",
    fieldTitleRequired: "Title *",
    placeholderTitle: "Short title of the request",
    fieldDescriptionRequired: "Description *",
    fieldImpactRequired: "Impact *",
    fieldPlannedStart: "Planned start",
    fieldPlannedEnd: "Planned end",
    fieldRollbackPlanRequired: "Rollback plan *",
    createChange: "Create request",
    backToChanges: "← Changes",
    notFoundTitle: "Request not found",
    notFoundDescription: "This request does not exist or you don't have access to it.",
    submitToCabTitle: "Submit to CAB",
    submitToCabDescription: "Send this request for CAB review and approval.",
    submitToCab: "Submit to CAB",
    cabReviewTitle: "CAB review",
    cabReviewDescription: "Approve or reject this change request.",
    inProgress: "In progress…",
    approve: "Approve",
    reject: "Reject",
    rejectCommentLabel: "Rejection comment (optional)",
    rejectCommentPlaceholder: "Reason for rejection...",
    requestDetailTitle: "Request details",
    fieldDates: "Dates",
    fieldImpact: "Impact",
    fieldRollbackPlan: "Rollback plan",
    rollbackNotSet: "— Not provided",
    domainRequired: "Domain required",
    calendarTitle: "Change calendar",
    calendarSubtitle: "Changes with a planned start date.",
    monthlyView: "Monthly view",
    backToChangesList: "← Change list",
    cabPendingChip: (n: number) => `${n} pending CAB`,
    plannedStartLabel: (date: string) => `Planned start: ${date}`,
    plannedEndLabel: (date: string) => `Planned end: ${date}`,
    createdAt: (date: string) => `Created on ${date}`,
    updatedAt: (date: string) => `Updated on ${date}`,
    typeLabels: {
      standard: "Standard",
      normal: "Normal",
      emergency: "Emergency",
    } as Record<string, string>,
    statusLabels: {
      draft: "Draft",
      submitted: "Submitted",
      cab_review: "CAB review",
      approved: "Approved",
      rejected: "Rejected",
      scheduled: "Scheduled",
      in_progress: "In progress",
      completed: "Completed",
      failed: "Failed",
      cancelled: "Cancelled",
    } as Record<string, string>,
    riskLabels: {
      low: "Low",
      medium: "Medium",
      high: "High",
      critical: "Critical",
    } as Record<string, string>,
  },
  knowledge: {
    title: "Knowledge",
    listSubtitle: "Knowledge base: procedures, FAQ and guides.",
    newArticle: "New article",
    filters: "Filters",
    filterCategory: "Category",
    allCategories: "All categories",
    documentation: "Documentation →",
    checkUrl: "Check the domain URL.",
    colTitle: "Title",
    colCategory: "Category",
    colTags: "Tags",
    colVisibility: "Visibility",
    colPublishedAt: "Published on",
    colViews: "Views",
    draft: "Draft",
    visibilityPublic: "Public",
    visibilityTechniciansOnly: "Technicians only",
    visibilityTechniciansShort: "Technicians",
    emptyTitle: "No article",
    emptyDescription: "Create your first article to start your knowledge base.",
    breadcrumbNew: "New",
    newArticleHeading: "New article",
    prefilledFromTicket: "Pre-filled from a ticket. Complete it then create the article.",
    fillBelow: "Fill in the information below.",
    sectionArticle: "Article",
    sectionMetadata: "Metadata",
    fieldTitleRequired: "Title *",
    fieldContentRequired: "Content *",
    fieldCategory: "Category",
    fieldAssetTypeOptional: "Asset type (optional)",
    fieldTags: "Tags (comma-separated)",
    fieldVisibility: "Visibility",
    placeholderTitle: "Article title",
    placeholderContent: "Markdown or plain text content...",
    placeholderTags: "e.g. printer, error, paper",
    createArticle: "Create article",
    creating: "Creating…",
    notFoundTitle: "Article not found",
    notFoundDescription: "This article does not exist or you don't have access to it.",
    metricViews: "Views",
    metricHelpful: "Helpful",
    metricNotHelpful: "Not helpful",
    sectionContent: "Content",
    editArticleHeading: "Edit article",
    editPanelTitle: "Editing",
    backToArticle: "Back to article",
    publishedOn: (date: string) => `Published on ${date}`,
    categoryLabels: {
      procedure: "Procedure",
      faq: "FAQ",
      guide: "Guide",
      reference: "Reference",
      troubleshooting: "Troubleshooting",
    } as Record<string, string>,
  },
  contracts: {
    listTitle: "Contracts",
    listSubtitle: "List of contracts with filters by type.",
    newContract: "New contract",
    filters: "Filters",
    allTypes: "All types",
    colReference: "Reference",
    colLabel: "Label",
    colType: "Type",
    colSupplier: "Supplier",
    colStart: "Start",
    colEnd: "End",
    colAmount: "Amount (€)",
    csvFilePrefix: "contracts",
    emptyTitle: "No contract registered",
    emptyDescription: "Create your first contract to track warranties, maintenance and deadlines.",
    checkUrl: "Check the domain URL.",
    documentation: "Documentation",
    breadcrumbNew: "New",
    fillBelow: "Fill in the information below.",
    sectionIdentification: "Identification",
    sectionPeriod: "Period",
    sectionCoveredAssets: "Covered assets",
    sectionNotes: "Notes",
    fieldReferenceRequired: "Reference *",
    fieldLabelRequired: "Label *",
    fieldTypeRequired: "Type *",
    fieldStartRequired: "Start *",
    fieldEndRequired: "End *",
    fieldSupplier: "Supplier",
    fieldAmount: "Amount (€)",
    fieldNoticeDays: "Notice (days)",
    fieldAutoRenewal: "Automatic renewal",
    fieldAutoRenewalShort: "Auto renewal",
    placeholderReference: "e.g. GAR-2025-001",
    placeholderLabel: "e.g. Manufacturer warranty",
    placeholderAmount: "Amount",
    placeholderNotesOptional: "Optional notes",
    createContract: "Create contract",
    backList: "← Contract list",
    notFoundTitle: "Contract not found",
    notFoundDescription: "This contract does not exist or you don't have access to it.",
    detailTitle: "Contract details",
    fieldReference: "Reference",
    fieldType: "Type",
    fieldLabel: "Label",
    fieldStart: "Start",
    fieldEnd: "End",
    assetsSelected: (n: number) => `${n} asset(s) selected`,
    typeLabels: {
      garantie: "Warranty",
      maintenance: "Maintenance",
      leasing: "Leasing",
      credit_bail: "Lease purchase",
      licence: "License",
    } as Record<string, string>,
  },
  assignments: {
    listTitle: "Assignments",
    listDescription: "Track assets assigned to beneficiaries.",
    newCta: "New assignment",
    filters: "Filters",
    filterAllStatuses: "All statuses",
    columnAsset: "Asset",
    columnAssignee: "Assignee",
    columnStart: "Start",
    columnExpectedEnd: "Expected end",
    statusActive: "Active",
    statusReturned: "Returned",
    statusOverdue: "Overdue",
    statusCancelled: "Cancelled",
    emptyTitle: "No assignments",
    emptyDescription: "Create a first assignment to get started.",
    breadcrumbDashboard: "Dashboard",
    breadcrumbShort: "Assignments",
    breadcrumbNew: "New",
    newTitle: "New assignment",
    newCaption: "Assign an asset to a beneficiary.",
    sectionAssignment: "Assignment",
    sectionPeriod: "Period",
    sectionReason: "Reason",
    fieldAssetRequired: "Asset *",
    selectAssetPlaceholder: "Select an asset",
    fieldAssignee: "Assignee",
    assigneeSelfFallback: "You",
    typeTemporary: "Temporary",
    typePermanent: "Permanent",
    fieldStartDateRequired: "Start date *",
    fieldExpectedEndDate: "Expected end date",
    fieldReasonOptional: "Reason (optional)",
    creating: "Creating…",
    createCta: "Create assignment",
    backToList: "← Back to assignments",
    notFoundTitle: "Assignment not found",
    notFoundBody: "This assignment does not exist or you do not have access to it.",
    beneficiaryLabel: "Beneficiary:",
    returnTitle: "Return the asset",
    returnDescription: "Closes the assignment, records the return date and puts the asset back in stock.",
    returnCta: "Return the asset",
    returning: "In progress…",
    returnConfirm: "Close this assignment and put the asset back in stock?",
    sectionInfo: "Details",
    fieldAsset: "Asset",
    fieldBeneficiary: "Beneficiary",
    fieldStart: "Start",
    fieldExpectedEnd: "Expected end",
    fieldActualEnd: "Actual end",
    fieldLinkedTicket: "Linked ticket",
    fieldReason: "Reason",
    editTitle: "Edit",
    fieldConditionReturn: "Condition at return",
    fieldContractSigned: "Contract signed",
  },
};

export { extraFr, extraEn };
